In [ ]:
import numpy as np

# 산술 연산

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
arr - arr 

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr**arr

array([[    1,     4,    27],
       [  256,  3125, 46656]])

## 브로드캐스팅

### 1. 스칼라

In [ ]:
arr + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
10 - arr

array([[9, 8, 7],
       [6, 5, 4]])

In [ ]:
arr*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
arr/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [ ]:
arr//3

array([[0, 0, 1],
       [1, 1, 2]])

In [ ]:
arr**3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [ ]:
arr > 3

array([[False, False, False],
       [ True,  True,  True]])

### 2. 배열

In [ ]:
arr2 = np.array([100, 200, 300])
arr2

array([100, 200, 300])

In [ ]:
arr 

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2

array([100, 200, 300])

In [ ]:
arr + arr2 

array([[101, 202, 303],
       [104, 205, 306]])

In [ ]:
arr*arr2 

array([[ 100,  400,  900],
       [ 400, 1000, 1800]])

In [ ]:
arr3 = np.array([[100],[200]])
arr3 

array([[100],
       [200]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3

array([[100],
       [200]])

In [ ]:
arr + arr3 

array([[101, 102, 103],
       [204, 205, 206]])

In [ ]:
arr.shape, arr3.shape

((2, 3), (2, 1))

# ufunc 유니버셜 함수 

**단항 유니버셜 함수**  

|Function|설명|
|---|---| 
|abs, fabs|각 원소의 절대값. 복소수가 아닌 경우 fabs를 쓰면 빠른 연산이 가능|
|sqrt|각 원소의 제곱근 계산(arr**0.5)|
|square|각 원소의 제곱을 계산(arr**2)|
|exp|각 원소에 지수e^x 계산|
|log, log10, log2, log1p|자연로그, 밑10인 로그, 밑2인 로그, log(1+x)|
|sign|각 원소의 부호(양수 1, 영 0, 음수 -1)|
|ceil|각 원소의 값보다 같거나 큰 정수 중 가장 작은 값|
|floor|각 원소의 값보다 같거나 작은 정수 중 가장 큰 값|
|rint|각 원소의 소수자리를 반올림|
|modf|각 원소의 몫과 나머지를 각각의 배열로 반환|
|isnan|각 원소가 NaN인지 아닌지. 불리언 배열로 반환|
|isfinite, isinf|각 원소가 유한한지, 무한한지. 불리언 배열로 반환|
|cos, cosh, sin, sinh, tan, tanh|일반 삼각함수, 쌍곡삼각함수|
|arccos, arccosh, arcsin, arcsinh, arctan, arctanh|역삼각함수|





In [ ]:
arr = np.arange(-3, 3).reshape(3, -1)
arr

array([[-3, -2],
       [-1,  0],
       [ 1,  2]])

In [ ]:
np.exp(arr)

array([[0.04978707, 0.13533528],
       [0.36787944, 1.        ],
       [2.71828183, 7.3890561 ]])

In [ ]:
np.floor(arr)

array([[-3., -2.],
       [-1.,  0.],
       [ 1.,  2.]])

In [ ]:
np.isinf([np.inf, -np.inf, 1, np.nan])

array([ True,  True, False, False])


**이항 유니버셜함수**  

|Function|설명|
|---|---|
|add|두 배열의 같은 위치의 원소끼리 합함|
|subtract|첫번째 배열의 원소에서 두번째 배열의 원소를 뺌|
|multiply|같은 위치의 원소끼리 곱함|
|divide, floor_divide|첫번째 배열의 원소를 두번째 배열의 원소를 나눔. floor는 몫만 취함|
|power|첫번째 매열의 원소를 두번째 배열의 원소만큼 제곱함|
|maximum, fmax|각 배열의 두 원소 중 큰 값을 반환. fmax는 NaN 무시|
|minimum, fmin|각 배열의 두 원소 중 작은 값을 반환. fmax는 NaN 무시|
|mod|첫번째 배열의 원소를 두번째 배열의 원소로 나눈 나머지|
|copysign|첫번째 배열의 원소의 기호를 두번째 배열의 원소의 기호로 바꿈|
|greater, greater_equal, less, less_equal, less, less_equal,|각 두 원소 간의 비교 연산(<, <=, >, >=, ==, !=)를 불리언 배열로 반환|

In [ ]:
arr1 = np.arange(8).reshape(2, -1)
arr2 = np.arange(-40, 40, 10).reshape(2, -1)
print(arr1)
print(arr2)

[[0 1 2 3]
 [4 5 6 7]]
[[-40 -30 -20 -10]
 [  0  10  20  30]]


In [ ]:
np.maximum(arr1, arr2)

array([[ 0,  1,  2,  3],
       [ 4, 10, 20, 30]])

In [ ]:
np.subtract(arr1, arr2)

array([[ 40,  31,  22,  13],
       [  4,  -5, -14, -23]])

In [ ]:
np.subtract(arr2, arr1)

array([[-40, -31, -22, -13],
       [ -4,   5,  14,  23]])

In [ ]:
np.multiply(arr1, arr2)

array([[  0, -30, -40, -30],
       [  0,  50, 120, 210]])

# 기본 통계 메서드

In [ ]:
arr = np.random.randn(200, 500)
arr.shape

(200, 500)

In [ ]:
arr.sum()    # ndarray의 메서드 이용

-596.3978294521196

In [ ]:
np.sum(arr)     # numpy의 최상위 함수를 이용 

-596.3978294521196

In [ ]:
arr.mean()   # ndarray의 메서드 이용

-0.005963978294521196

In [ ]:
np.mean(arr)  # numpy의 최상위 함수를 이용 

-0.005963978294521196

In [ ]:
np.var(arr)

1.0031665274816948

axis 인자로 축 지정 !

In [ ]:
arr.shape

(200, 500)

In [ ]:
arr.mean(axis=0).shape

(500,)

In [ ]:
arr.mean(axis=1).shape

(200,)

In [ ]:
arr.sum(axis=0).shape

(500,)

In [ ]:
arr.sum(axis=1).shape

(200,)

# 연습문제 1

## 1번
시드를 100으로 고정한 후, (10x10) 크기의 난수배열을 생성하라. (난수배열은 정규분포를 따른다)  
이후 배열에서 가장 큰 값과 가장 작은 값, 그리고 그것의 위치를 찾아내보자.

In [ ]:
'''
max 값은 2.0346075615049335, max의 인덱스는 74
'''

In [ ]:
'''
max 값은 2.0346075615049335, max의 인덱스는 74
'''

## 2번
주어진 배열을 이용하여 다음과 같은 결과값을 만들어보자

In [ ]:
arr1 = np.arange(10).reshape(5,2)
arr2 = np.array([[-1, 0]])

In [ ]:
'''
array([[ 0,  0],
       [-2,  0],
       [-4,  0],
       [-6,  0],
       [-8,  0]])
'''

## 3번
주어진 배열과 mean함수를 이용하여 다음과 같은 결과를 만들어보자

In [ ]:
np.random.seed(200)
arr = np.random.randn(30).reshape(2,3,5)

In [ ]:
'''
0.20183667368310884
'''

In [ ]:
'''
array([[ 0.2571224 ,  0.06460539,  0.90381548],
       [-0.07401127, -0.14847703,  0.20796507]])
'''

# any, all

In [ ]:
arr = np.array([True, False, True])
arr.any()

True

In [ ]:
arr = np.array([True, False, True])
arr.all()

False

In [ ]:
arr = np.array([0, 0, 3])
arr.any()

True

In [ ]:
arr = np.array([0, 0, 1])
arr.all()

False

In [ ]:
arr = np.array([1, 1, 1])
arr.all()

True

In [ ]:
arr = np.array([5, -1, np.inf])
arr.all()

True

# where

In [ ]:
xarr = np.array([100, 200, 300, 400])
yarr = np.array([1, 2, 3, 4])
cond = np.array([True, False, True, False])

In [ ]:
result = np.where(cond, xarr, yarr)
result

array([100,   2, 300,   4])

In [ ]:
np.where(xarr>200, max(xarr), 0)

array([  0,   0, 400, 400])

In [ ]:
np.where(xarr%3==0, 1, 0 )

array([0, 0, 1, 0])

# sort

## arr.sort()

In [ ]:
np.random.seed(10)
arr = np.random.randint(1, 100, size=10)
arr

array([10, 16, 65, 29, 90, 94, 30,  9, 74,  1])

In [ ]:
arr.sort()
arr

array([ 1,  9, 10, 16, 29, 30, 65, 74, 90, 94])

##np.sort()

In [ ]:
np.random.seed(20)
arr = np.random.randint(1, 100, size=10)
np.sort(arr)

array([10, 16, 21, 23, 29, 72, 76, 91, 91, 96])

In [ ]:
arr

array([91, 16, 96, 29, 91, 10, 21, 76, 23, 72])

In [ ]:
-np.sort(-arr)

array([96, 91, 91, 76, 72, 29, 23, 21, 16, 10])

# 선형대수


|Function|설명|
|---|---|
|dot|내적|
|dialog|정사각 행렬의 대각/비대각 원소를 1차원 배열로 반환하거나, 1차원 배열을 대각선 원소로 하고 나머지는 0으로 채운 단위행렬 반환|
|trace|행렬의 대각선 원소의 합을 계산|
|linalg.det|행렬식을 계산(ad-bc)|
|linalg.eig|정사각행렬의 고유값, 고유벡터를 계산|
|linalg.inv|정사각행렬의 역행렬을 계산|
|linalg.solve|A가 정사각 행렬일 때, Ax = b를 만족하는 x를 구함|
|linalg.svd|특이값 분해(SVD)를 계산|

## dot


In [ ]:
x = np.random.randint(-5, 5, size=10)
y = np.random.randint(-10, 10, size=10)
x.shape, y.shape

((10,), (10,))

In [ ]:
x.dot(y)

-3

In [ ]:
np.dot(x, y)

-3

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[2, -3], [1, 6], [-1, 2]])
x.shape, y.shape

((2, 3), (3, 2))

In [ ]:
np.dot(x, y)

array([[ 1, 15],
       [ 7, 30]])

## matmul

In [ ]:
a = np.random.randint(-3, 3, 10).reshape(2, 5)
b = np.random.randint(0, 5, 15).reshape(5, 3)
a.shape, b.shape

((2, 5), (5, 3))

In [ ]:
ab = np.matmul(a, b)
print(ab.shape,'\n')
print(ab)

(2, 3) 

[[  6   0   6]
 [-14  -6  -4]]


In [ ]:
np.matmul(b, a)

ValueError: ignored

In [ ]:
ab2 = a@b
print(ab2.shape, '\n')
print(ab2)

(2, 3) 

[[  6   0   6]
 [-14  -6  -4]]


In [ ]:
c = np.arange(24).reshape(2, 3, 4)
d = np.arange(2*4*5).reshape(2, 4, 5)
c.shape, d.shape

((2, 3, 4), (2, 4, 5))

In [ ]:
arr = np.matmul(c, d)
arr

array([[[  70,   76,   82,   88,   94],
        [ 190,  212,  234,  256,  278],
        [ 310,  348,  386,  424,  462]],

       [[1510, 1564, 1618, 1672, 1726],
        [1950, 2020, 2090, 2160, 2230],
        [2390, 2476, 2562, 2648, 2734]]])

In [ ]:
arr.shape

(2, 3, 5)

# 연습문제 2

## 1번
주어진 배열을 이용하여 다음과 같은 연산을 해보자.  
원소의 값이 0보다 클 경우 배열의 가장 큰 값으로, 0보다 작거나 같을 경우 배열의 가장 작은 값으로 만들어보자.

In [ ]:
np.random.seed(253)
arr = np.random.randn(20).reshape(4,5)

In [ ]:
'''
array([[ 3.30666723, -1.38283849,  3.30666723,  3.30666723,  3.30666723],
       [-1.38283849, -1.38283849, -1.38283849, -1.38283849, -1.38283849],
       [-1.38283849,  3.30666723,  3.30666723,  3.30666723,  3.30666723],
       [-1.38283849, -1.38283849,  3.30666723,  3.30666723,  3.30666723]])
'''

## 2번
주어진 배열에서 0이 포함된 컬럼이 있는지 없는지 파악해보자.  
- 0이 있는 컬럼이 있다면 True  
- 없다면 False


In [ ]:
np.random.seed(2531)
arr = np.random.randint(0,3, (3,4))